language: R
cache: packages
warnings_are_errors: true
sudo: false

matrix:
  include:
  - r: release
    os: linux
  - r: devel
    os: linux
  - r: release
    os: osx

r_packages:
- Rcpp
- RcppArmadillo
- ggplot2
- igraph
- mclust
- knitr
- rmarkdown
- viridis
- formatR

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov(type ="all")'

r_build_args: "--html"

r_check_args: "--as-cran --timings"
